export const types = {
  uiRefreshImage: '[ui] Refresh image on menus',
  uiLoadingDeleting: '[ui] Loading while deleting something',
  uiOpenModal: '[ui] Open modal',
  uiCloseModal: '[ui] Close modal',
  uiLoading: '[ui] Loading',
  uiLoadingRegister: '[ui] LoadingRegister',
  uiLoadingLogin: '[ui] LoadingLogin',
  uiLoadingUpdatingClient: '[ui] Loading updating client',
  uiLoadingClients: '[ui] Loading clients',
  uiLoadingChangingPassword: '[ui] Loading changing password',
  uiLoadingGoingToMercadoPago: '[ui] Loading goint to mercado pago',

  appointmentSetActive: '[appointment] Set Active',
  appointmentLogout: '[appointment] Logout appointment',

  evetStartAddNew: '[appointment] Start add new',
  appointmentAddNew: '[appointment] Add new',
  clearActiveAppointment: '[appointment] Clear active appointment',
  appointmentUpdated: '[appointment] Appointment updated',
  appointmentDeleted: '[appointment] Appointment deleted',
  appointmentLoaded: '[appointment] Appointments loaded',

  getClients: '[client] Get all clients',
  clientSelected: '[client] Set the selected client',
  clientStartLogin: '[client] Start login',
  clientLogin: '[client] Login',
  clientStartRegister: '[client] Start Register',
  clientLogout: '[client] Logout',
  clientAppointments: '[client] Set the current client appointments',

  getServices: '[services] Get all services',
  serviceSelected: '[services] Set the selected service',

  getUsers: '[users] Get all users',
  userSelected: '[users] Set the selected user',
  userAppointments: '[users] Set the selected user appointments',
  userStartLogin: '[users] Start login',
  userLogin: '[users] Login',
  userLogout: '[users] Logout',
}
